FROM golang:1.18

WORKDIR /usr/src/flight-log-api-gateway

# pre-copy/cache go.mod for pre-downloading dependencies and only
# redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
COPY ./templates /usr/src/flight-log-api-gateway/templates
COPY ./documents /usr/src/flight-log-api-gateway/documents
COPY .env.local .env

RUN go get -d -v ./...
RUN go install -v ./...

CMD ["flight-log-api-gateway"]

